PG_RAY_BOX_HOST: "${PG_RAY_BOX_HOST}|localhost"
PG_RAY_BOX_PORT: "${PG_RAY_BOX_PORT}|5432"
PG_RAY_BOX_USERNAME: "${PG_RAY_BOX_USERNAME}|postgres"
PG_RAY_BOX_PASSWORD: "${PG_RAY_BOX_PASSWORD}|123456"

PG_RAY_BOX_DATABASE: "${PG_RAY_BOX_DATABASE}|ray_box"
