REDIS_MASTER_NODES: ${REDIS_MASTER_NODES}|localhost:6379
REDIS_MASTER_PASSWORD: ${REDIS_MASTER_PASSWORD}|
REDIS_MASTER_PORT: ${REDIS_MASTER_PORT}|6379

# redis使用的context超时时间，单位：秒
REDIS_TIMEOUT_DURATION: ${REDIS_TIMEOUT_DURATION}|2